import { CommonProps } from "@mui/material/OverridableComponent";
import { colors } from "../../../assets/colors";

export const styles: Record<string, CommonProps["style"]> = {
  root: {
    borderRadius: 8,
    border: `1px solid ${colors.vistaBlue}`,
  },
  headerTableCell: {
    padding: 4,
    flex: 1,
    borderBottom: `1px solid ${colors.vistaBlue}`,
    borderRight: `1px solid ${colors.vistaBlue}`,
    display: "flex",
    backgroundColor: colors.powderBlue,
    alignItems: "center",
    fontWeight: "bold",
  },
  tableCell: {
    flex: 1,
    borderRight: `1px solid ${colors.vistaBlue}`,
    flexDirection: "row",
    borderBottom: `1px solid ${colors.vistaBlue}`,
    backgroundColor: "white",
    display: "flex",
    textAlign: "start",
    justifyContent: "flex-start",
    alignItems: "center",
    padding: 4,
  },
  resultCell: {
    padding: 4,
    flex: 1,
    borderBottom: `1px solid ${colors.vistaBlue}`,
    borderRight: `1px solid ${colors.vistaBlue}`,
    display: "flex",
    backgroundColor: colors.powderBlue,
    alignItems: "center",
    justifyContent: "flex-end",
    fontWeight: "bold",
    width: 200,
  },
  rightAlign: {
    justifyContent: "flex-end",
  },
  valueCell: {
    flex: 1,
    borderRight: `1px solid ${colors.vistaBlue}`,
    flexDirection: "row",
    borderBottom: `1px solid ${colors.vistaBlue}`,
    display: "flex",
    textAlign: "start",
    justifyContent: "flex-end",
    alignItems: "center",
    padding: 4,
    backgroundColor: "white",
  },
  accountCell: {
    flex: 1,
    borderRight: `1px solid ${colors.vistaBlue}`,
    flexDirection: "row",
    borderBottom: `1px solid ${colors.vistaBlue}`,
    display: "flex",
    textAlign: "start",
    fontWeight: "bold",
    alignItems: "center",
    padding: 4,
    backgroundColor: "white",
  },
  tableRow: {
    display: "flex",
    flexDirection: "row",
    height: 30,
    width: "calc(100vw - 8rem)",
  },
  tableHeader: {
    width: "calc(100vw - 10rem)",
    padding: "1rem",
    backgroundColor: `${colors.vistaBlue}`,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: `2px solid ${colors.tifanyBlue}`,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  downloadBtn: {
    borderRadius: 8,
    width: 200,
    backgroundColor: "#1D6F42",
  },
  tableTitle: {
    fontSize: 20,
    fontWeight: "bold",
  },
};
